In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import h5py 

In [2]:
N_match_top_in_event_chi2 = []
jet_parton_index_chi2 = []
parton_jet_index_chi2 = []

N_match_top_in_event_del = []
jet_parton_index_del = []
parton_jet_index_del = []
jet_pt_del = []
jet_phi_del = []
jet_eta_del = []
jet_barcode_del = []
jet_mass_del = []
jet_btag_del = []

N_0_del = 0
N_1_del = 0
N_2_del = 0

N_0_chi2 = 0
N_1_chi2 = 0
N_2_chi2 = 0
for i in range(1,11):
    PREFIX_chi2 = "./output/output_chi2/"
    PREFIX_del = "./output/output_delta/"
    chi2_file = ""
    delta_file = ""
    seq_chi2 = (PREFIX_chi2, "output_", "chi2_", str(i), ".h5")
    seq_delta = (PREFIX_del, "output_", "del_", str(i), ".h5")

    with h5py.File(chi2_file.join(seq_chi2), 'r') as f:
        #print(f.keys())
        _N_match_top_in_event_chi2 = f['N_match_top_in_event']
        _jet_parton_index_chi2 = f['jet_parton_index']
        _parton_jet_index_chi2 = f['parton_jet_index']

        for x in _N_match_top_in_event_chi2:
            N_match_top_in_event_chi2.append(x)
        
        for y in _jet_parton_index_chi2:
            jet_parton_index_chi2.append(y)

        for z in _parton_jet_index_chi2:
            parton_jet_index_chi2.append(z)

    with h5py.File(delta_file.join(seq_delta), 'r') as g:
        #print(g.keys())
        _N_match_top_in_event_del = g['N_match_top_in_event']
        _jet_parton_index_del = g['jet_parton_index']
        _parton_jet_index_del = g['parton_jet_index']
        _jet_pt_del = g['jet_pt']
        _jet_phi_del = g['jet_phi']
        _jet_eta_del = g['jet_eta']
        _jet_barcode_del = g['jet_barcode']
        _jet_mass_del = g['jet_mass']
        _jet_btag_del = g['jet_btag']
                

        for a in _N_match_top_in_event_del:
            N_match_top_in_event_del.append(a)
        
        for b in _jet_parton_index_del:
            jet_parton_index_del.append(b)

        for c in _parton_jet_index_del:
            parton_jet_index_del.append(c)

        for d in _jet_pt_del:
            jet_pt_del.append(d)

        for h in _jet_eta_del:
            jet_eta_del.append(h)

        for j in _jet_phi_del:
            jet_phi_del.append(j)
        
        for k in _jet_mass_del:
            jet_mass_del.append(k)
        
        for l in _jet_btag_del:
            jet_btag_del.append(l)
            

In [3]:
for i in range(len(N_match_top_in_event_del)):
    if N_match_top_in_event_del[i] == 2:
        print(jet_parton_index_del[i])

3.  0.  4. nan  1.  5. nan]
[ 5.  0. nan  3. nan  2.  4. nan  1.]
[nan  2.  4.  3.  1.  5.  0.]
[nan  3.  0.  5.  1.  4.  2.]
[3. 2. 5. 0. 4. 1.]
[ 0.  3.  1.  5.  2.  4. nan]
[ 0.  4.  2. nan nan  5. nan  3.  1.]
[ 4.  3.  1.  0.  5.  2. nan nan]
[ 3.  1.  0. nan  5.  4.  2.]
[ 2.  3. nan  5.  0.  4.  1.]
[ 3.  0. nan nan nan  1.  5.  4.  2. nan]
[ 5.  2.  3.  0. nan  4.  1. nan nan]
[ 3.  0.  2.  1. nan  4.  5.]
[nan  0.  1.  3. nan  5.  2.  4.]
[ 3.  1.  2.  5.  4.  0. nan nan nan]
[ 3. nan  1.  4. nan  5.  0.  2.]
[ 3.  0.  5.  2.  4. nan  1. nan]
[ 3.  0.  5. nan  1.  4.  2.]
[ 4.  0.  5.  2. nan  3.  1. nan]
[ 5.  0.  2.  1. nan  3.  4.]
[nan  5.  4.  1.  3.  2.  0.]
[ 0.  1.  5.  2.  3.  4. nan]
[ 3.  5.  4. nan  0.  2.  1.]
[ 4.  1.  3.  0. nan  2.  5.]
[ 2.  0.  1.  3.  4. nan nan  5.]
[5. 0. 4. 1. 3. 2.]
[ 1. nan nan  4.  5.  0.  3. nan  2.]
[0. 5. 3. 1. 2. 4.]
[ 3.  2.  1.  5.  0.  4. nan]
[ 3. nan  0.  5. nan  2.  1.  4.]
[nan  1.  3.  5.  4.  0.  2. nan nan]
[nan  1.  5. n

In [4]:
def gaussian_fit(target):
    mean = np.average(target)
    _sigma = 0
    for i in range(len(target)):
        _sigma += (target[i] - mean)**2
    sigma = np.sqrt(_sigma/len(target))

    return mean, sigma 

In [5]:
# class jet_cand_properties():
#         def __init__(self, idx):
#             self.idx = idx
#             self.pt = jet_pt_chi2[self.idx]
#             self.eta = jet_eta_chi2[self.idx]
#             self.phi = jet_phi_chi2[self.idx]
#             self.mass = jet_mass_chi2[self.idx]
#             self.px = self.pt*np.cos(self.phi)
#             self.py = self.pt*np.sin(self.phi)
#             self.pz = self.pt*np.sinh(self.eta)
#             self.e = np.sqrt( (self.px**2 + self.py**2 + self.pz**2) + self.mass**2 )

#     def cal_W_inv(jet1, jet2):
#         part_1 = (jet1.e + jet2.e)**2
#         part_2 = (jet1.px + jet2.px)**2
#         part_3 = (jet1.py + jet2.py)**2
#         part_4 = (jet1.pz + jet2.pz)**2
#         return np.sqrt( part_1 - part_2 - part_3 - part_4 )

#     def cal_top_inv(jet1, jet2, jet3):
#         part_1 = (jet1.e + jet2.e + jet3.e)**2
#         part_2 = (jet1.px + jet2.px, jet3.px)**2
#         part_3 = (jet1.py + jet2.py, jet3.py)**2
#         part_4 = (jet1.pz + jet2.pz, jet3.pz)**2
#         return np.sqrt( part_1 - part_2 - part_3 - part_4 )

In [6]:
W_plus_inv_jet = []
W_minus_inv_jet = []

tmp = 0
tmp_p = 0

for i in range(len(N_match_top_in_event_del)):
    if N_match_top_in_event_del[i] == 2:
        for j in range(len(jet_pt_del[i])):
            if jet_parton_index_del[i][j] == 1:
                #jet_idx = int(parton_jet_index[i][j])
                pt_1 = jet_pt_del[i][j]
                eta_1 = jet_eta_del[i][j]
                phi_1 = jet_phi_del[i][j]
                mass_1 = jet_mass_del[i][j]
                px_1 = pt_1*np.cos( phi_1 )
                py_1 = pt_1*np.sin( phi_1 )
                pz_1 = pt_1*np.sinh( eta_1 )
                e_1 = np.sqrt( (px_1**2 + py_1**2 + pz_1**2 ) + mass_1**2 ) 
                #print("W daughter 1:", j, pt_1, eta_1, phi_1, px_1, py_1, pz_1, e_1)

            if jet_parton_index_del[i][j] == 2:
                #jet_idx = int(parton_jet_index[i][j])
                pt_2 = jet_pt_del[i][j]
                eta_2 = jet_eta_del[i][j]
                phi_2 = jet_phi_del[i][j]
                mass_2 = jet_mass_del[i][j]
                px_2 = pt_2*np.cos( phi_2 )
                py_2 = pt_2*np.sin( phi_2 )
                pz_2 = pt_2*np.sinh( eta_2 )
                e_2 = np.sqrt( (px_2**2 + py_2**2 + pz_2**2 ) + mass_2**2 )
                #print("W daughter 2:", j, pt_2, eta_2, phi_2, px_2, py_2, pz_2, e_2)

            if jet_parton_index_del[i][j] == 4:
                #jet_idx = int(parton_jet_index[i][j])
                pt_4 = jet_pt_del[i][j]
                eta_4 = jet_eta_del[i][j]
                phi_4 = jet_phi_del[i][j]
                mass_4 = jet_mass_del[i][j]
                px_4 = pt_4*np.cos( phi_4 )
                py_4 = pt_4*np.sin( phi_4 )
                pz_4 = pt_4*np.sinh( eta_4 )
                e_4 = np.sqrt( (px_4**2 + py_4**2 + pz_4**2 ) + mass_4**2 )
                #print("W- daughter 1:", j, pt_4, eta_4, phi_4, px_4, py_4, pz_4, e_4)

            if jet_parton_index_del[i][j] == 5:
                #jet_idx = int(parton_jet_index[i][j])
                pt_5 = jet_pt_del[i][j]
                eta_5 = jet_eta_del[i][j]
                phi_5 = jet_phi_del[i][j]
                mass_5 = jet_mass_del[i][j]
                px_5 = pt_5*np.cos( phi_5 )
                py_5 = pt_5*np.sin( phi_5 )
                pz_5 = pt_5*np.sinh( eta_5 )
                e_5 = np.sqrt( (px_5**2 + py_5**2 + pz_5**2 ) + mass_5**2 )
                #print("W- daughter 2:", j, pt_5, eta_5, phi_5, px_5, py_5, pz_5, e_5)

    tmp = np.sqrt( ( e_1 + e_2 )**2 - ( px_1 + px_2 )**2 - ( py_1 + py_2 )**2 - ( pz_1 + pz_2 )**2 )
    tmp_p = np.sqrt( ( e_4 + e_5 )**2 - ( px_4 + px_5)**2 - ( py_4 + py_5 )**2 - ( pz_4 + pz_5 )**2 )

    W_plus_inv_jet.append(tmp)
    W_minus_inv_jet.append(tmp_p)

In [7]:
mean_W, sigma_W = gaussian_fit(W_plus_inv_jet)
print(mean_W, sigma_W)

77.01848031090302 17.77440075175323


In [8]:
t_inv_jet = []
t_bar_inv_jet = []

tmp = 0
tmp_p = 0

for i in range(len(N_match_top_in_event_del)):
    if N_match_top_in_event_del[i] == 2:
        for j in range(len(jet_parton_index_del[i])):
            
            if jet_parton_index_del[i][j] == 0:
                #jet_idx = int(parton_jet_index[i][j])
                pt_0 = jet_pt_del[i][j]
                eta_0 = jet_eta_del[i][j]
                phi_0 = jet_phi_del[i][j]
                mass_0 = jet_mass_del[i][j]
                px_0 = pt_0*np.cos( phi_0 )
                py_0 = pt_0*np.sin( phi_0 )
                pz_0 = pt_0*np.sinh( eta_0 )
                e_0 = np.sqrt( (px_0**2 + py_0**2 + pz_0**2 ) + mass_0**2 ) 
                #print("b cand:", j, pt_0, eta_0, phi_0, px_0, py_0, pz_0, e_0)

            if jet_parton_index_del[i][j] == 1:
                #jet_idx = int(parton_jet_index[i][j])
                pt_1 = jet_pt_del[i][j]
                eta_1 = jet_eta_del[i][j]
                phi_1 = jet_phi_del[i][j]
                mass_1 = jet_mass_del[i][j]
                px_1 = pt_1*np.cos( phi_1 )
                py_1 = pt_1*np.sin( phi_1 )
                pz_1 = pt_1*np.sinh( eta_1 )
                e_1 = np.sqrt( (px_1**2 + py_1**2 + pz_1**2 ) + mass_1**2 ) 
                #print("W daughter 1:", j, pt_1, eta_1, phi_1, px_1, py_1, pz_1, e_1)

            if jet_parton_index_del[i][j] == 2:
                #jet_idx = int(parton_jet_index[i][j])
                pt_2 = jet_pt_del[i][j]
                eta_2 = jet_eta_del[i][j]
                phi_2 = jet_phi_del[i][j]
                mass_2 = jet_mass_del[i][j]
                px_2 = pt_2*np.cos( phi_2 )
                py_2 = pt_2*np.sin( phi_2 )
                pz_2 = pt_2*np.sinh( eta_2 )
                e_2 = np.sqrt( (px_2**2 + py_2**2 + pz_2**2 ) + mass_2**2 )
                #print("W daughter 2:", j, pt_2, eta_2, phi_2, px_2, py_2, pz_2, e_2)

            if jet_parton_index_del[i][j] == 3:
                #jet_idx = int(parton_jet_index[i][j])
                pt_3 = jet_pt_del[i][j]
                eta_3 = jet_eta_del[i][j]
                phi_3 = jet_phi_del[i][j]
                mass_3 = jet_mass_del[i][j]
                px_3 = pt_3*np.cos( phi_3 )
                py_3 = pt_3*np.sin( phi_3 )
                pz_3 = pt_3*np.sinh( eta_3 )
                e_3 = np.sqrt( (px_3**2 + py_3**2 + pz_3**2 ) + mass_3**2 )
                #print("b bar cand:", j, pt_3, eta_3, phi_3, px_3, py_3, pz_3, e_3)

            if jet_parton_index_del[i][j] == 4:
                #jet_idx = int(parton_jet_index[i][j])
                pt_4 = jet_pt_del[i][j]
                eta_4 = jet_eta_del[i][j]
                phi_4 = jet_phi_del[i][j]
                mass_4 = jet_mass_del[i][j]
                px_4 = pt_4*np.cos( phi_4 )
                py_4 = pt_4*np.sin( phi_4 )
                pz_4 = pt_4*np.sinh( eta_4 )
                e_4 = np.sqrt( (px_4**2 + py_4**2 + pz_4**2 ) + mass_4**2 )
                #print("W- daughter 1:", j, pt_4, eta_4, phi_4, px_4, py_4, pz_4, e_4)

            if jet_parton_index_del[i][j] == 5:
                #jet_idx = int(parton_jet_index[i][j])
                pt_5 = jet_pt_del[i][j]
                eta_5 = jet_eta_del[i][j]
                phi_5 = jet_phi_del[i][j]
                mass_5 = jet_mass_del[i][j]
                px_5 = pt_5*np.cos( phi_5 )
                py_5 = pt_5*np.sin( phi_5 )
                pz_5 = pt_5*np.sinh( eta_5 )
                e_5 = np.sqrt( (px_5**2 + py_5**2 + pz_5**2 ) + mass_5**2 )
                #print("W- daughter 2:", j, pt_5, eta_5, phi_5, px_5, py_5, pz_5, e_5)

        tmp = np.sqrt( (e_0 + e_1 + e_2)**2 - (px_0 + px_1 + px_2)**2 - (py_0 + py_1 + py_2)**2 - (pz_0 + pz_1 + pz_2)**2 )
        tmp_p = np.sqrt( (e_3 + e_4 + e_5)**2 - (px_3 + px_4 + px_5)**2 - (py_3 + py_4 + py_5)**2 - (pz_3 + pz_4 + pz_5)**2 )
        t_inv_jet.append(tmp)
        t_bar_inv_jet.append(tmp_p)


In [9]:
mean_top, sigma_top = gaussian_fit(t_inv_jet)
print(mean_top, sigma_top)

160.98522325555072 27.490585334320205


In [10]:
for j in range(len(N_match_top_in_event_del)):
    if N_match_top_in_event_del[j] == 0: 
        N_0_del += 1
    elif N_match_top_in_event_del[j] == 1:
        N_1_del += 1 
    elif N_match_top_in_event_del[j] == 2:
        N_2_del += 1
    else :
        Print("error occur!")

In [11]:
purity_del = N_2_del/(N_0_del + N_1_del + N_2_del)
print(purity_del)

0.3245299812102366


In [23]:
def to_matrix(target_1, target_2):
    len_parton = len(target_1)
    len_jet = len(target_2)
    _matrix = np.zeros(len_parton*len_jet)
    matrix =  _matrix.reshape((len_parton, len_jet))
    for x in range(len_parton):
        _value = int(target_1[x])
        matrix[x][_value] = 1
            
    return matrix

result = []
correct_result = []
for i in range(len(N_match_top_in_event_chi2)):
#for i in range(0,1):
    _delta = to_matrix(parton_jet_index_del[i], jet_parton_index_del[i])
    _chi2 = to_matrix(parton_jet_index_chi2[i], jet_parton_index_chi2[i])

    print("{0}, \n{1}".format(_delta, _chi2))
    _compare = _delta == _chi2
    _result = np.sum( _compare == False )/2
    print(_result)
    result.append( np.sum( _compare == False )/2 )
    if _result == 0: 
        correct = 2
    elif _result <= 3: 
        correct = 1
    else :
        correct = 0
    #print( correct/2 )
    correct_result.append( correct )

 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]], 
[[0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]
1.0
[[0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]], 
[[0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]
4.0
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]], 
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
3.0
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 

In [25]:
for k in range(len(correct_result)):
    if correct_result[k] == 0: 
        N_0_chi2 += 1
    elif correct_result[k] == 1:
        N_1_chi2 += 1 
    elif correct_result[k] == 2:
        N_2_chi2 += 1
    else :
        Print("error occur!")

In [26]:
purity_chi2 = N_2_chi2/(N_0_chi2 + N_1_chi2 + N_2_chi2)
print(purity_chi2)

0.013136207805907173


In [27]:
N_2_del + N_1_del + N_0_del

182014

In [28]:
N_2_del

59069

In [29]:
N_2_chi2

2391

In [30]:
np.sum(np.array(N_match_top_in_event_chi2, dtype='object') == 2.0)

182014