In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import h5py 

In [10]:
N_match_top_in_event_chi2 = []
jet_parton_index_chi2 = []
parton_jet_index_chi2 = []

N_match_top_in_event_del = []
jet_parton_index_del = []
parton_jet_index_del = []
N_0_del = 0
N_1_del = 0
N_2_del = 0

N_0_chi2 = 0
N_1_chi2 = 0
N_2_chi2 = 0
for i in range(1,11):
    PREFIX_chi2 = "./output/output_chi2/"
    PREFIX_del = "./output/output_delta/"
    chi2_file = ""
    delta_file = ""
    seq_chi2 = (PREFIX_chi2, "output_", "chi2_", str(i), ".h5")
    seq_delta = (PREFIX_del, "output_", "del_", str(i), ".h5")

    with h5py.File(chi2_file.join(seq_chi2), 'r') as f:
        #print(f.keys())
        _N_match_top_in_event_chi2 = f['N_match_top_in_event']
        _jet_parton_index_chi2 = f['jet_parton_index']
        _parton_jet_index_chi2 = f['parton_jet_index']

        for x in _N_match_top_in_event_chi2:
            N_match_top_in_event_chi2.append(x)
        
        for y in _jet_parton_index_chi2:
            jet_parton_index_chi2.append(y)

        for z in _parton_jet_index_chi2:
            parton_jet_index_chi2.append(z)

    with h5py.File(delta_file.join(seq_delta), 'r') as g:
        #print(g.keys())
        _N_match_top_in_event_del = g['N_match_top_in_event']
        _jet_parton_index_del = g['jet_parton_index']
        _parton_jet_index_del = g['parton_jet_index']

        for a in _N_match_top_in_event_del:
            N_match_top_in_event_del.append(a)
        
        for b in _jet_parton_index_del:
            jet_parton_index_del.append(b)

        for c in _parton_jet_index_del:
            parton_jet_index_del.append(c)
            
for j in range(len(N_match_top_in_event_del)):
    if N_match_top_in_event_del[j] == 0: 
        N_0_del += 1
    elif N_match_top_in_event_del[j] == 1:
        N_1_del += 1 
    elif N_match_top_in_event_del[j] == 2:
        N_2_del += 1
    else :
        Print("error occur!")

    

In [11]:
purity_del = N_2_del/(N_0_del + N_1_del + N_2_del)
print(purity_del)

0.3245299812102366


In [32]:
def to_matrix(target_1, target_2):
    len_parton = len(target_1)
    len_jet = len(target_2)
    _matrix = np.zeros(len_parton*len_jet)
    matrix =  _matrix.reshape((len_parton, len_jet))
    for x in range(len_parton):
        _value = int(target_1[x])
        matrix[x][_value] = 1
            
    return matrix

result = []
correct_result = []
#for i in range(len(N_match_top_in_event_chi2)):
for i in range(0,1):
    _delta = to_matrix(parton_jet_index_del[i], jet_parton_index_del[i])
    _chi2 = to_matrix(parton_jet_index_chi2[i], jet_parton_index_chi2[i])

    print("{0}, \n{1}".format(_delta, _chi2))
    _compare = _delta == _chi2
    _result = np.sum( _compare == False )/2
    print(_result)
    result.append( np.sum( _compare == False )/2 )
    if _result == 0: 
        correct = 2
    elif _result <= 3: 
        correct = 1
    else :
        correct = 0
    #print( correct/2 )
    correct_result.append( correct )

[[0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]], 
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]]
2.0


In [13]:
for k in range(len(correct_result)):
    if correct_result[k] == 0: 
        N_0_chi2 += 1
    elif correct_result[k] == 1:
        N_1_chi2 += 1 
    elif correct_result[k] == 2:
        N_2_chi2 += 1
    else :
        Print("error occur!")

In [14]:
purity_chi2 = N_2_chi2/(N_0_chi2 + N_1_chi2 + N_2_chi2)
print(purity_chi2)

0.013136352148735812


In [15]:
N_2_del + N_1_del + N_0_del

182014

In [16]:
N_2_del

59069

In [17]:
N_2_chi2

2391

In [27]:
np.sum(np.array(N_match_top_in_event_chi2, dtype='object') == 2.0)

182014