In [1]:
import h5py
import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict
from scipy import integrate, optimize
from iminuit import Minuit
from tqdm import tqdm
from itertools import product
from multiprocessing import Pool

In [2]:
JSF = 0.98
mass = [170, 171, 172, 173, 174, 175, 176]
for m in mass:
    h5py_file1 = h5py.File(f'ttbar_testing_final_mass_variation_JSF=1.00/ttbar_testing_{m}_gev.h5', "r")
    h5py_file2 = h5py.File(f'ttbar_testing_final_mass_variation_JSF={JSF}/ttbar_testing_{m}_gev.h5', "r+")
    dataset = h5py_file2['jet_features/pt']
    dataset[:] = h5py_file1['jet_features/pt'][:]*JSF
    h5py_file2.close()

In [3]:
JSF = 1.02
mass = [170, 171, 172, 173, 174, 175, 176]
for m in mass:
    h5py_file1 = h5py.File(f'ttbar_testing_final_mass_variation_JSF=1.00/ttbar_testing_{m}_gev.h5', "r")
    h5py_file2 = h5py.File(f'ttbar_testing_final_mass_variation_JSF={JSF}/ttbar_testing_{m}_gev.h5', "r+")
    dataset = h5py_file2['jet_features/pt']
    dataset[:] = h5py_file1['jet_features/pt'][:]*JSF
    h5py_file2.close()

In [4]:
h5py_file1['jet_features/pt'][:]

array([[204.74872 ,  60.93544 ,  60.931118, ...,   0.      ,   0.      ,
          0.      ],
       [268.50995 ,  62.778442,  30.559166, ...,   0.      ,   0.      ,
          0.      ],
       [143.35538 ,  99.752205,  83.05969 , ...,   0.      ,   0.      ,
          0.      ],
       ...,
       [157.39824 , 125.97514 ,  93.636215, ...,   0.      ,   0.      ,
          0.      ],
       [ 69.09838 ,  45.86541 ,  37.97825 , ...,   0.      ,   0.      ,
          0.      ],
       [128.10052 ,  81.71694 ,  76.95326 , ...,   0.      ,   0.      ,
          0.      ]], dtype=float32)

In [7]:
h5py_file2 = h5py.File(f'ttbar_testing_final_mass_variation_JSF=0.98/ttbar_testing_{m}_gev.h5', "r+")
h5py_file2['jet_features/pt'][:]

array([[200.65375 ,  59.716732,  59.712498, ...,   0.      ,   0.      ,
          0.      ],
       [263.13974 ,  61.522873,  29.947983, ...,   0.      ,   0.      ,
          0.      ],
       [140.48827 ,  97.757164,  81.3985  , ...,   0.      ,   0.      ,
          0.      ],
       ...,
       [154.25027 , 123.45564 ,  91.7635  , ...,   0.      ,   0.      ,
          0.      ],
       [ 67.716415,  44.9481  ,  37.218685, ...,   0.      ,   0.      ,
          0.      ],
       [125.53851 ,  80.0826  ,  75.4142  , ...,   0.      ,   0.      ,
          0.      ]], dtype=float32)

In [8]:
h5py_file2 = h5py.File(f'ttbar_testing_final_mass_variation_JSF=1.02/ttbar_testing_{m}_gev.h5', "r+")
h5py_file2['jet_features/pt'][:]

array([[208.84369 ,  62.15415 ,  62.14974 , ...,   0.      ,   0.      ,
          0.      ],
       [273.88016 ,  64.03401 ,  31.17035 , ...,   0.      ,   0.      ,
          0.      ],
       [146.22249 , 101.747246,  84.72089 , ...,   0.      ,   0.      ,
          0.      ],
       ...,
       [160.5462  , 128.49464 ,  95.508934, ...,   0.      ,   0.      ,
          0.      ],
       [ 70.48035 ,  46.78272 ,  38.737812, ...,   0.      ,   0.      ,
          0.      ],
       [130.66254 ,  83.35128 ,  78.492325, ...,   0.      ,   0.      ,
          0.      ]], dtype=float32)